import {LanguageCode} from 'paperback-extensions-common'

export const reverseLangCode: {[x: string]: LanguageCode} = {
    '_unknown': LanguageCode.UNKNOWN,
    'BENGALI': LanguageCode.BENGALI,
    'BULGARIAN': LanguageCode.BULGARIAN,
    'BRAZILIAN': LanguageCode.BRAZILIAN,
    'CHINEESE': LanguageCode.CHINEESE,
    'CZECH': LanguageCode.CZECH,
    'GERMAN': LanguageCode.GERMAN,
    'DANISH': LanguageCode.DANISH,
    'ENGLISH': LanguageCode.ENGLISH,
    'SPANISH': LanguageCode.SPANISH,
    'FINNISH': LanguageCode.FINNISH,
    'FRENCH': LanguageCode.FRENCH,
    'GREEK': LanguageCode.GREEK,
    'CHINEESE_HONGKONG': LanguageCode.CHINEESE_HONGKONG,
    'HUNGARIAN': LanguageCode.HUNGARIAN,
    'INDONESIAN': LanguageCode.INDONESIAN,
    'ISRELI': LanguageCode.ISRELI,
    'INDIAN': LanguageCode.INDIAN,
    'IRAN': LanguageCode.IRAN,
    'ITALIAN': LanguageCode.ITALIAN,
    'JAPANESE': LanguageCode.JAPANESE,
    'KOREAN': LanguageCode.KOREAN,
    'LITHUANIAN': LanguageCode.LITHUANIAN,
    'MONGOLIAN': LanguageCode.MONGOLIAN,
    'MEXIAN': LanguageCode.MEXIAN,
    'MALAY': LanguageCode.MALAY,
    'DUTCH': LanguageCode.DUTCH,
    'NORWEGIAN': LanguageCode.NORWEGIAN,
    'PHILIPPINE': LanguageCode.PHILIPPINE,
    'POLISH': LanguageCode.POLISH,
    'PORTUGUESE': LanguageCode.PORTUGUESE,
    'ROMANIAN': LanguageCode.ROMANIAN,
    'RUSSIAN': LanguageCode.RUSSIAN,
    'SANSKRIT': LanguageCode.SANSKRIT,
    'SAMI': LanguageCode.SAMI,
    'THAI': LanguageCode.THAI,
    'TURKISH': LanguageCode.TURKISH,
    'UKRAINIAN': LanguageCode.UKRAINIAN,
    'VIETNAMESE': LanguageCode.VIETNAMESE
}